### ISSUE TITLE
Bug: Modell "_alle_gebaeude_kvie" - Fehlende Features

### ISSUE THREAD

**Issue by Vbialk** [kreis-viersen/qgis-models-and-scripts#18]
Das Modell zum Download aller Gebäude im Kreis liefert eine falsche Anzahl an Features zurück (251.229).
Der WFS meldet hingegen deutlich mehr Objekte (260.290).
Wird in der Auswahlliste nur die Gemeide Viersen festgelegt, liefert das Modell exakt 50.000 Objekte, was dem Feature-Limit des WFS entspricht.

Die Vermutung liegt nahe, dass die Objekte durch das Feature-Limit des WFS verloren gehen. 
Hier könnte nur gegensteuern werden, wenn entweder das Feature-Limit erhöht oder mit Index/Count in der GetFeature Anfrage gearbeitet wird. Soweit ich weiß geht das mit den nativen QGIS Mitteln nicht. 

<details>
  <summary>Anzahl Features Modell (fehlerhaft)</summary>

![image](https://user-images.githubusercontent.com/73645103/133067268-c4c7aec3-8724-447c-a7ff-4ea7327f68ea.png)

</details>

<details>
  <summary>Anzahl Features WFS</summary>

![image](https://user-images.githubusercontent.com/73645103/133067337-659c1b58-4519-41ad-887d-58cf467fd62e.png)

</details>

<details>
  <summary>Anzahl Features Gemeinde Viersen (fehlerhaft)</summary>

![image](https://user-images.githubusercontent.com/73645103/133067708-5ce71651-31a1-4f89-b6fb-810744c2a1cd.png)

</details>

Anmerkung: Die ca. 9000 fehlenden Objekte stammen tatsächlich aus der Gemeinde Viersen (insgesamt 59.062)

**Comment by pathmapper** [comment]
Danke für den Report 👍  ja da laufen wir aktuell in das Server Limit.

> Anmerkung: Die ca. 9000 fehlenden Objekte stammen tatsächlich aus der Gemeinde Viersen (insgesamt 59.062)

Sicher, dass Gemeinde Viersen 59.062 Objekte und nicht 59.061 hat? 260.290 - 251.229 = 9.061

**Comment by Vbialk** [comment]
Es sind 59.061 ;-) 
Hatte mich mit dem Index beim zweiten Durchlauf vertan

**Comment by pathmapper** [comment]
Fix in https://github.com/kreis-viersen/qgis-models-and-scripts/pull/20
